#From: https://dev.to/willvelida/pushing-container-images-to-github-container-registry-with-github-actions-1m6b

name: Deploy Images to GHCR

on:
  pull_request:
    types: [created, labeled, edited]

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './sample-packages/docker'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/ch-rob/test-image-from-action:latest
              docker push ghcr.io/ch-rob/test-image-from-action:latest
